buildVariable: true
category:
- SERIF
familyName: Noto Serif NP Hmong
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifNPHmong.designspace
