buildVariable: true
category:
- SERIF
familyName: Noto Serif Nyiakeng Puachue Hmong
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
sources:
- NotoSerifNyiakengPuachueHmong.designspace
